const expectedCid = 'bafkreicc33kqomysk74kc6t6ikjyxeu7hpu6kusxzhwxpojtfwf7ukh2om'

export default expectedCid

export const expectedBz2Cid = 'bafkreihgvqh5yupmvozoa47ullhgzqj7erjch4fwmnbekadkvxotyyxjsy'
